# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               面壁者.陈
tagline:             'to think your life and record my story'
description:         'Just a little site for my work and musings.'
url:                 localhost:4000
baseurl:             /
paginate:            5

# About/contact
author:
  name:              alex chen
  url:               https://twitter.com/mdo
  email:             baypm2009@gmail.com

# Custom vars
version:             1.0.0
